version: '3.7'
services:
  configserver:
    image: config-server-gradle
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "config-server"
networks:
  backend:
    driver: bridge
